# Generated by Django 4.2.4 on 2023-08-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ilast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uniformcolor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="ユニフォームカラー")),
            ],
        ),
        migrations.RenameField(
            model_name="ilastopost",
            old_name="ccategory",
            new_name="category",
        ),
        migrations.AddField(
            model_name="ilastopost",
            name="uniformcolor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="ilast.uniformcolor",
                verbose_name=" ユニフォームカラー",
            ),
            preserve_default=False,
        ),
    ]
